# Even Fibonacci numbers
# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.
#
# フィボナッチ数列は項は直前の2項の合計となる。1と2で始まる最初の10項のは以下の通り
# 1,2,3,5,8,13,21,34,55,89
# 項の値が4,000,000 以下のフィボナッチ数列の偶数の総和を求めよ

MAX_VALUE = 4000000
fibo = Array.new

# initialize
first  = 1
second = 2
fibo << first
fibo << second
sum = 2

loop do
  term = first + second
  break if term > MAX_VALUE

  if term % 2 == 0
    sum += term
  end

  fibo << term
  first = second
  second = term
end

p fibo
p sum
